const CreditsERC20 = artifacts.require("CreditsERC20");
const CreditsERC20Test = artifacts.require("CreditsERC20Test");
const Launchpad = artifacts.require("Launchpad");
const MailERC721 = artifacts.require("MailERC721");
const MailERC721Test = artifacts.require("MailERC721Test");
const MailExtension = artifacts.require("MailExtension");
const FeedExtension = artifacts.require("FeedExtension");
const FeedExtensionTest = artifacts.require("FeedExtensionTest");
const FeedExtensionTest2 = artifacts.require("FeedExtensionTest2");
const CheckFeedExtension = artifacts.require("CheckFeedExtension");
const CheckMailExtension = artifacts.require("CheckMailExtension");
const Feed = artifacts.require("Feed");
const FeedTest = artifacts.require("FeedTest");
const NoReply = artifacts.require("NoReply");
const MailERC721Attack_1 = artifacts.require("MailERC721Attack_1");
const MailERC721Attack_2 = artifacts.require("MailERC721Attack_2");
const FeedAttack_1 = artifacts.require("FeedAttack_1");
const FeedAttack_2 = artifacts.require("FeedAttack_2");
const FeedAttack_2_Aux = artifacts.require("FeedAttack_2_Aux");
const LaunchpadAttack_1 = artifacts.require("LaunchpadAttack_1");
const LaunchpadAttack_2 = artifacts.require("LaunchpadAttack_2");
const Contacts = artifacts.require("Contacts");
const FeedExtensionAttack = artifacts.require("FeedExtensionAttack");

module.exports = function(deployer, network, accounts){
    deployer.then(async () => {
        await deployer.deploy(CreditsERC20);
        await deployer.deploy(CreditsERC20Test);
        await deployer.deploy(Launchpad, CreditsERC20.address);
        await deployer.deploy(CheckFeedExtension);
        await deployer.link(CheckFeedExtension, [MailERC721, MailERC721Test, Feed, FeedTest]);
        await deployer.deploy(FeedExtensionAttack);
        await deployer.deploy(CheckMailExtension);
        await deployer.link(CheckMailExtension, [MailERC721, MailERC721Test]);
        await deployer.deploy(MailERC721, CreditsERC20.address, Launchpad.address);
        await deployer.deploy(MailERC721Test, CreditsERC20.address, Launchpad.address);
        await deployer.deploy(MailExtension, MailERC721.address, CreditsERC20.address);
        await deployer.deploy(FeedExtension, CreditsERC20.address, web3.utils.toWei("1", "ether"));
        await deployer.deploy(FeedExtensionTest, CreditsERC20.address, web3.utils.toWei("1", "ether"));
        await deployer.deploy(FeedExtensionTest2, CreditsERC20.address, web3.utils.toWei("1", "ether"));
        await deployer.deploy(Feed, MailERC721Test.address, accounts[0], 1296000, "0x0000000000000000000000000000000000000000", web3.utils.toWei("1", "ether"), 0);
        await deployer.deploy(FeedTest, MailERC721Test.address, accounts[0], 1296000, FeedExtension.address, web3.utils.toWei("2", "ether"), 0);
        await deployer.deploy(NoReply, CreditsERC20.address, MailERC721.address);
        await deployer.deploy(MailERC721Attack_1, MailERC721.address);
        await deployer.deploy(MailERC721Attack_2, MailERC721.address);
        await deployer.deploy(FeedAttack_1);
        await deployer.deploy(FeedAttack_2);
        await deployer.deploy(FeedAttack_2_Aux);
        await deployer.deploy(LaunchpadAttack_1, Launchpad.address, CreditsERC20.address);
        await deployer.deploy(LaunchpadAttack_2, Launchpad.address, CreditsERC20.address);
        await deployer.deploy(Contacts, MailERC721.address);
    });
};